# Copyright Nixort <https://github.com/Nixort> 2026.
#
# License: GNU General Public License v3.0 only.
# You can find the license file in the project root.
#
# Federated CFR Connect Protocol (FCP).
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /bindings/java
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /bindings/csharp/src/LibFcp
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /bindings/go
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
